# Accept namespaces as args. This requires tilt > v0.22.7

load('./api/Tiltfile', 'load_kubefwd')

config.define_string_list("namespaces")
cfg = config.parse()

namespaces = cfg.get('namespaces', [])

# Creates a button that refreshes the kubefwd without
# requiring new credentials.
load_kubefwd(namespaces)